#include <stdio.h>
#include <stdlib.h>

/* project euler problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

int main() 

{
	int a = 0, b = 1;
	int fibo = 0;
	int sum_fibo = 0;
	int max = 4000000;
	
	while (fibo < max)
	{
		fibo = a + b;
		a = b;
		b = fibo;
		
		if (fibo % 2 == 0)
		{
			sum_fibo += fibo;
		}
	}
	
	printf("The sum of even-valued Fibonnacci sequence terms whose values do not exceed four million is %d", sum_fibo);
	
	return 0;
}
